name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: "master-${GITHUB_SHA::8}"
    
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      - name: Extract short sha
        shell: bash
        run: echo "##[set-output name=sha;]${GITHUB_SHA::8}"
        id: extract_sha

      - name: Use version
        run: |
          echo "${{steps.extract_branch.outputs.branch}}-${{steps.extract_sha.outputs.sha}}"
