name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: "master-${GITHUB_SHA::8}"
    
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          VERSION="master-${GITHUB_SHA::8}"
          echo "DOCKER_TAG=${VERSION}" >> $GITHUB_ENV
      - name: Use version
        run: |
          echo ${DOCKER_TAG}
