name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: "master-${GITHUB_SHA::8}"
  BRANCH: "${GITHUB_REF}"
    
jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set version
        run: |
          echo ${VERSION}
          echo ${BRANCH}
