name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2    
        run: |
          VERSION="master-${GITHUB_SHA::8}"
          echo ${VERSION}
