name: ci

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  VERSION: "master-${GITHUB_SHA::8}"

jobs:
  test:
    runs-on: ubuntu-latest
    outputs:
      build_id: ${{ steps.build_id.outputs.BUILD_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: Generate build ID
        id: build_id
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and publish image
        uses: docker/build-push-action@v2
        with:
          context: .
          tags: |
            ghcr.io/redr0bin/test:${{ steps.build_id.outputs.BUILD_ID }}
          push: true
