name: release

on:
  push:
    tags: 
    - 'v*.*.*'

jobs:
  push-release:
    name: Tag application release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Echo tag
        command: echo ${{ github.ref_name }}


