name: release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  push-release:
    name: Tag application release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate build ID
        id: source_image
        run: |
          branch=master
          sha=$(git rev-list -n 1 ${{ github.ref_name }} | cut -c1-8)
          echo ${sha}
          source_image=$(curl -s -H 'Authorization: Bearer ${{ secrets.GH_PAT}}' -H "Accept: application/vnd.github.v3+json" https://api.github.com/orgs/redr0bin/packages/container/test/versions | jq -r --arg sha "${sha}" '.[] | select(.metadata.container.tags[] | contains($sha)) | .metadata.container.tags[0]')
          echo ${source_image}
          echo "::set-output name=IMAGE_TAG::${source_image}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.CR_PAT }}

      - name: Fetch source image
        run: docker pull ghcr.io/redr0bin/test:${{ steps.source_image.outputs.IMAGE_TAG }}

      - name: Tag release image
        run: |-
          docker tag ghcr.io/redr0bin/test:${{ steps.source_image.outputs.IMAGE_TAG }} \
          ghcr.io/redr0bin/test:${{ github.ref_name }}
          docker push  ghcr.io/redr0bin/test:${{ github.ref_name }}
