name: release

on:
  push:
    tags:
    - 'v*.*.*'

jobs:
  push-release:
    name: Tag application release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate build ID
        id: source_image
        run: |
          branch=${GITHUB_REF##*/}
          sha=$(git rev-list -n 1 ${{ github.ref_name }} | cut -c1-8)
          echo "::set-output name=IMAGE_TAG::${branch}-${sha}"

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Set release tag
        uses: koraykoska/retag-docker-image@0.2.4
        with:
          registry: ghcr.io/redr0bin
          name: test
          old_tag: ${{ steps.source_image.outputs.IMAGE_TAG }}
          new_tag: ${{ github.ref_name }}
